config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :statuses
  get '/profiles/friends', to: 'profiles#friends', as: :logged_in_homepage
  resources :profiles, param: :username
  resources :relationships, only: [:create, :destroy]
  resources :exclusions, only: [:create, :destroy]
  get 'profiles/load_profile/:id', to: 'profiles#load_profile', as: 'load_profile' # TODO: change to username
  get '/profiles/:id/statuses', to: 'profiles#statuses', as: :past_statuses # TODO: change to username
  get '/site', to: 'site#index', as: :logged_out_homepage
  get '/site/terms_of_use', to: 'site#terms_of_use', as: :terms_of_use
  get '/site/privacy_policy', to: 'site#privacy_policy', as: :privacy_policy
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/user' => "profiles#friends", :as => :user_root
  root 'site#index'
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_and_belongs_to_many :user
  has_many :statuses, dependent: :destroy
  has_one :latest_status, -> { Status.latest_statuses_for_profiles }, class_name: "Status"
  has_many :posts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :active_exclusions, class_name: "Exclusion", foreign_key: "blocker_id", dependent: :destroy
  has_many :blocking, through: :active_exclusions, source: :blocked
  has_many :passive_exclusions, class_name: "Exclusion", foreign_key: "blocked_id", dependent: :destroy
  has_many :blockers, through: :passive_exclusions, source: :blocker

  validates :username, presence: true, uniqueness: true

  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  # Blocks a user.
  def block(other_user)
    active_exclusions.create(blocked_id: other_user.id)
  end

  # Unfollows a user.
  def unblock(other_user)
    active_exclusions.find_by(blocked_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def blocking?(other_user)
    blocking.include?(other_user)
  end

  # TODO: make unblocked a scope and use it in the following_and_unblocked below
  def unblocked
    blockers_ids = blockers&.pluck(:id)
    blockers_ids.push(id)
    blockers_ids.blank? ? Profile.all : Profile.all.where.not(id: blockers_ids)
  end

  def following_and_unblocked
    blockers_ids = blockers&.pluck(:id)
    blocking_ids = blocking&.pluck(:id)
    blocked_ids = blockers_ids.union(blocking_ids)
    blocked_ids.blank? ? following : following.where.not(id: blocked_ids)
  end

  def all_not_blocked
    blockers_ids = blockers&.pluck(:id)
    blocking_ids = blocking&.pluck(:id)
    blocked_ids = blockers_ids.union(blocking_ids)
    blocked_ids.blank? ? Profile.all : Profile.all.where.not(id: blocked_ids)
  end

  scope :alphabetized_asc, -> { order(name: :asc) }
  scope :alphabetized_desc, -> { order(name: :desc) }
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: %i[ show edit update destroy ]
  before_action :set_profile_by_id, only: %i[ statuses ]

  # GET /profiles or /profiles.json
  def index
    @profiles = current_user.profiles.first.unblocked
  end

  # GET /profiles/1 or /profiles/1.json
  def show
    @posts = Post.by_user(@profile)
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    authorize @profile
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        current_user.profiles << @profile
        # format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.html { redirect_to profiles_path, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    authorize @profile
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    authorize @profile
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def load_profile
    # Rails.logger.debug params
    session[:current_profile] = Profile.find(params[:id])
    # Rails.logger.debug session[:current_profile].inspect
    session[:current_profile][:last_loaded] = Time.zone.now
    session[:current_profile].save
    respond_to do |format|
      format.html {
        if (params[:forward])
          redirect_to params[:forward], notice: 'Profile loaded.'
        else
          redirect_to logged_in_homepage_path, notice: 'Profile loaded.'
        end
      }
      format.json { head :no_content }
    end
  end

  # GET /profiles/friends or /profiles/friends.json
  def friends
    # TODO: `first` is a hack, fix it
    # @current_user_latest_status = Status.where(profile: current_user.profiles.first).order("id DESC").limit(1).first
    # current user follows [profile, profile, ...]
    # @following = current_user.profiles.first.following
    # statusus = Status.where(profile: in array), group by max id
    # @statuses = Status.where(profile: )
  end

  # GET /profiles/1/statuses or /profiles/1/statuses.json
  def statuses
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  def set_profile
    # profile_to_find = params[:id] || current_user.profiles.first.id
    # @profile = Profile.find(profile_to_find)
    # This will also grab an id as the username param if an id was sent instead of a username in the route
    begin
      # 1 || 2 are for not statuses
      # 3 is for statuses # TODO: Consider breaking this check out into a different method
      @profile = Profile.find_by(username: params[:username]) || Profile.find_by(id: params[:username])
    rescue ActiveRecord::RecordNotFound => e
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  def set_profile_by_id
    begin
      @profile = Profile.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  # Only allow a list of trusted parameters through.
  def profile_params
    params.require(:profile).permit(:name, :bio, :username)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def get_block_path_helper(current_profile, profile)
    return nil if current_profile == profile

    return button_to 'Unblock', exclusion_path(profile), method: :delete if current_profile.blocking?(profile)

    button_to 'Block', exclusions_path(blocked_id: profile.id)
  end

  def get_follow_path_helper(current_profile, profile)
    return nil if current_profile == profile

    return button_to 'Unfollow', relationship_path(profile), method: :delete if current_profile.following?(profile)

    button_to 'Follow', relationships_path(followed_id: profile.id)
  end
end

app/views/profiles/_blocked.html.erb
<h1>Blocked</h1>

<p>This user has blocked you.</p>

app/views/profiles/_blocking.html.erb
<%= get_block_path_helper(current_user.profiles.first, @profile) %>

<h1>Blocking</h1>

<p>You are blocking this user.</p>

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_area :username %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/_post.html.erb
<div>
  <strong><%= display_linked_profile_name post.author %></strong> left a message:<br>
  <%= post.content %><br>
  <%= post.created_at %>
  <% if post.author == current_user.profiles.first %>
    | <%= link_to "Edit", edit_post_path(post, profile_id: @profile.id) %>
    | <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>
<br>

app/views/profiles/_profile_details.html.erb
<%= link_to 'Edit', edit_profile_path(@profile) if current_user.profiles.first == @profile %>
<%= get_follow_path_helper(current_user.profiles.first, @profile) %>
<%= get_block_path_helper(current_user.profiles.first, @profile) %>
<%#= link_to 'Back', profiles_path %>

<p>
  <strong>Unique username:</strong>
  <%= @profile.username %>
</p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @profile.bio %>
</p>

app/views/profiles/_status.html.erb
<div>
  <strong><%= display_linked_profile_name profile %></strong> <%= status.content %><br>
  <%= status.created_at %>
  <% if status.profile == current_user.profiles.first %>
    | <%= link_to "Edit", edit_status_path(status) %>
    | <%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/profiles/_unblocked.html.erb
<%= render 'profile_details' %>

<%= link_to "View Past Statuses", past_statuses_path(@profile) %>

<h2>Wall</h2>
<%= link_to "Leave Message", new_post_path(profile_id: @profile.id) %>
<br><br>
<div id="wall_posts">
  <% @posts.each do |post| %>
    <%= render 'post', post: post %>
  <% end %>
</div>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

app/views/profiles/friends.html.erb
<h1>Logged-In Homepage</h1>

<h2>Updates</h2>
<h3>Your Status</h3>
<%= (render 'status', { profile: current_user.profiles.first, status: current_user.profiles.first.latest_status }) if current_user.profiles.first.latest_status.present? %>

<h3>Your Friends' Statuses</h3>
<% current_user.profiles.first.following_and_unblocked.alphabetized_asc.map do |profile| %>
  <%= (render 'status', { profile: profile, status: profile.latest_status || { content: '', created_at: '' } }) %>
<% end %>

app/views/profiles/index.html.erb
<h1>Find Friends</h1>

<table>
  <thead>
    <tr>
      <th>Unique Username</th>
      <th>Name</th>
      <th>Bio</th>
      <th colspan="2">Actions</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.username %></td>
        <td><%= link_to profile.name, profile %></td>
        <td><%= profile.bio %></td>
        <td><%= get_follow_path_helper(current_user.profiles.first, profile) %></td>
        <td><%= get_block_path_helper(current_user.profiles.first, profile) %></td>
        <% if current_user.profiles.first == profile %>
          <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
          <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

app/views/profiles/show.html.erb
<% if current_user.profiles.first.blocking?(@profile) %>
  <%= render "blocking" %>
<% elsif @profile.blocking?(current_user.profiles.first) %>
  <%= render "blocked" %>
<% else %>
  <%= render "unblocked" %>
<% end %>

app/views/profiles/statuses.html.erb
<%= render 'profile_details' %>

<%= link_to "View Wall", profile_path(@profile) %>

<h2>Past Statuses</h2>
<div id="past_statuses">
  <% @profile.statuses.map do |status| %>
    <%= (render 'status', { profile: @profile, status: status }) if @profile.latest_status.present? %>
  <% end %>
</div>