config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :statuses
  get '/profiles/friends', to: 'profiles#friends', as: :logged_in_homepage
  resources :profiles, param: :username
  resources :relationships, only: [:create, :destroy]
  resources :exclusions, only: [:create, :destroy]
  get 'profiles/load_profile/:id', to: 'profiles#load_profile', as: 'load_profile' # TODO: change to username
  get '/profiles/:id/statuses', to: 'profiles#statuses', as: :past_statuses # TODO: change to username
  get '/site', to: 'site#index', as: :logged_out_homepage
  get '/site/terms_of_use', to: 'site#terms_of_use', as: :terms_of_use
  get '/site/privacy_policy', to: 'site#privacy_policy', as: :privacy_policy
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/user' => "profiles#friends", :as => :user_root
  root 'site#index'
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: %i[ show edit update destroy ]

  # GET /statuses or /statuses.json
  def index
    @statuses = Status.all.where(profile: current_user.profiles.first.all_not_blocked)
  end

  # GET /statuses/1 or /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
    authorize @status
  end

  # POST /statuses or /statuses.json
  def create
    @status = Status.new(status_params.merge({profile_id: current_user.profiles.first.id}))

    respond_to do |format|
      if @status.save
        format.html { redirect_to logged_in_homepage_path, notice: "Status was successfully created." }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1 or /statuses/1.json
  def update
    authorize @status
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: "Status was successfully updated." }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1 or /statuses/1.json
  def destroy
    authorize @status
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: "Status was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def status_params
      params.require(:status).permit(:content, :profile_id)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= form_with(model: status) do |form| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
        <% status.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

<!--  <div class="field">-->
    <%#= form.label :profile_id %>
    <%#= form.text_field :profile_id %>
<!--  </div>-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status %>

app/views/statuses/index.html.erb
<h1>Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Profile</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.content %></td>
        <td><%= link_to status.profile.name, status.profile %></td>
<!--        <td><%#= link_to 'Show', status %></td>-->
        <% if current_user.profiles.first == status.profile %>
          <td><%= link_to 'Edit', edit_status_path(status) %></td>
          <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form', status: @status %>

app/views/statuses/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @status.profile_id %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>