config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :statuses
  get '/profiles/friends', to: 'profiles#friends', as: :logged_in_homepage
  resources :profiles, param: :username
  resources :relationships, only: [:create, :destroy]
  resources :exclusions, only: [:create, :destroy]
  get 'profiles/load_profile/:id', to: 'profiles#load_profile', as: 'load_profile' # TODO: change to username
  get '/profiles/:id/statuses', to: 'profiles#statuses', as: :past_statuses # TODO: change to username
  get '/site', to: 'site#index', as: :logged_out_homepage
  get '/site/terms_of_use', to: 'site#terms_of_use', as: :terms_of_use
  get '/site/privacy_policy', to: 'site#privacy_policy', as: :privacy_policy
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/user' => "profiles#friends", :as => :user_root
  root 'site#index'
end

app/models/post.rb
class Post < ApplicationRecord
  attr :author_profile

  belongs_to :profile

  scope :by_user, lambda { |user|
    where(:profile_id => user.id)
  }

  def author
    author_profile || Profile.find(self.author_id) # TODO: consider changing to find_by_id so you don't throw exceptions
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :load_profile, only: %i[ new edit ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.where(profile: current_user.profiles.first.all_not_blocked)
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    authorize @post
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params.merge({author_id: current_user.profiles.first.id}))

    respond_to do |format|
      if @post.save
        format.html { redirect_to Profile.find(post_params[:profile_id]), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    authorize @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    Rails.logger.debug 'about to authorize'
    authorize @post
    Rails.logger.debug 'authorized'
    @post.destroy
    Rails.logger.debug 'destroyed'
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # TODO: investigate if this should be used for profiles and statuses to prevent other users from editing
  # TODO: or check if it's preventing editing here because it was designed for create only
  def load_profile
    redirect_to logged_in_homepage_path and return if params[:profile_id].blank?

    @profile = Profile.find(params[:profile_id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:content, :profile_id, :author_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    Leaving message for<br />
    <%= @profile.name %>
  </div>

  <%= form.hidden_field :profile_id, value: @profile.id %>

<!--  <div class="field">-->
    <%#= form.label :author_id %>
    <%#= form.text_field :author_id %>
<!--  </div>-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Profile</th>
      <th>Author</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= link_to post.profile.name, post.profile %></td>
        <td><%= link_to post.author.name, post.author %></td>
<!--        <td><%#= link_to 'Show', post %></td>-->
        <% if current_user.profiles.first == post.author %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @post.profile_id %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.author_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>