config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :statuses
  get '/profiles/friends', to: 'profiles#friends', as: :logged_in_homepage
  resources :profiles, param: :username
  resources :relationships, only: [:create, :destroy]
  resources :exclusions, only: [:create, :destroy]
  get 'profiles/load_profile/:id', to: 'profiles#load_profile', as: 'load_profile' # TODO: change to username
  get '/profiles/:id/statuses', to: 'profiles#statuses', as: :past_statuses # TODO: change to username
  get '/site', to: 'site#index', as: :logged_out_homepage
  get '/site/terms_of_use', to: 'site#terms_of_use', as: :terms_of_use
  get '/site/privacy_policy', to: 'site#privacy_policy', as: :privacy_policy
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/user' => "profiles#friends", :as => :user_root
  root 'site#index'
end

app/views/layouts/_footer.html.erb
<br><br>
<hr>
&copy; 2021
<%= link_to 'Terms of Use', terms_of_use_path %>
<%= link_to 'Privacy Policy', privacy_policy_path %>
<%= link_to 'Report Issue', 'https://github.com/davemcg3/famupdates/issues/new' %>

app/views/layouts/_navbar.html.erb
<% if current_user.present? %>
  <%= profile_name_with_fallback(current_user) %>
  <br />
  <%= link_to "View Fam Statuses", logged_in_homepage_path %>
  <% if current_user.profiles.present? %>
    <%= link_to "View Profile", profile_path(username: current_user.profiles.first&.username || current_user.profiles.first&.id) %>
  <% end %>
  <%= link_to "Update Your Status", new_status_path %>
  <%= link_to 'Find New Fam', profiles_path %>
<% end %>
<%= navbar_user_link %>
<%= link_to "Register", new_user_registration_path if current_user.nil? %>
<% displayed_value = '' %>
<% flash.each do |key, value| %>
  <% next if (value == displayed_value) %>
  <% displayed_value = value %>
  <div class="alert alert-<%= key %> <%= key %>"><%= value %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fam Updates</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="twitter:card" content="summary" />
    <meta property="og:title" content="famupdates" />
    <meta property="og:description" content="Get updates from yo fam!" />
    <meta property="og:image" content="https://famupdates.com/images/friends-enjoying-company.jpg" />

    <link rel="apple-touch-icon" sizes="180x180" href="/images/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon/favicon-16x16.png">
    <link rel="manifest" href="/images/favicon/site.webmanifest">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <header>
      <h1><%= link_to "fam updates", (current_user.present? ? logged_in_homepage_path : logged_out_homepage_path) %><sup>alpha</sup></h1>
      <%= render 'layouts/navbar' %>
    </header>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>